### ISSUE TITLE
Files Unlinking from Series

### ISSUE THREAD

**Issue by Darken5** [japanesemediamanager/ShokoDesktop#529]
i have come across several series in my collection that are now showing as having 0 files and arent playing when i click play, but the files are all still there where they were when they were imported. 

on the "Files" tab in "Collection". its giving me the correct info under the Files Header, but under the Folder header it says Total File Count 0 (0.000 Bytes)

im also getting an error in the server log when i click play on one of these broken links

[2017-04-10 11:22:20:255] Error|SyncMethodInvoker.Invoke => <no type>.SyncInvokeGetVideoLocalsForAnime => JMMServiceImplementation.GetVideoLocalsForAnime System.ArgumentException: 'path' cannot be an empty string.
Parameter name: path
at Pri.LongPath.Path.NormalizeLongPath(String path, String parameterName) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\Direct\ScanRepository.cs:line 0
   at JMMServer.Entities.VideoLocal.GetMediaFromUser(Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal.cs:line 513
   at JMMServer.Entities.VideoLocal.ToContract(Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal.cs:line 506
   at System.Linq.Enumerable.WhereSelectListIterator2.MoveNext()
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at JMMServer.JMMServiceImplementation.GetVideoLocalsForAnime(Int32 animeID, Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\JMMServiceImplementation.cs:line 8317

**Comment by da3dsoul** [comment]
Is this on 3.7.0.6? I believe it was fixed.

**Comment by ElementalCrisis** [comment]
As far as I can tell, it's fixed in dailies. @Darken5 feel free to reopen this issue if it persists once 3.7.5.0 is released.
